# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stockswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox
)
from PyQt5.uic import loadUi

from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
from PyQt5 import QtGui
from PyQt5.QtCore import QDate, Qt, QSortFilterProxyModel
from datetime import datetime
import tkinter as tk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
from urllib.request import urlopen, Request
import pyqtgraph as pg
import re
from pip._vendor import requests
from PIL import ImageTk, Image  



class Window(QMainWindow) :
    def __init__(self,parent=None, date=20):
        """Initializer."""
        super().__init__(parent)
        QMainWindow.setObjectName("MainWindow")
        QMainWindow.resize(1000, 1000)
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.highlow = PlotWidget(self.centralwidget)
        self.highlow.setGeometry(QtCore.QRect(40, 240, 281, 231))
        self.highlow.setObjectName("highlow")
        self.volume = PlotWidget(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(40, 620, 281, 231))
        self.volume.setObjectName("volume")
        self.stockComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.stockComboBox.setGeometry(QtCore.QRect(70, 60, 231, 32))
        self.stockComboBox.setMouseTracking(True)
        self.stockComboBox.setTabletTracking(True)
        self.stockComboBox.setAcceptDrops(True)
        self.stockComboBox.setEditable(True)
        self.stockComboBox.setCurrentText("")
        self.stockComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.stockComboBox.setMinimumContentsLength(0)
        self.stockComboBox.setObjectName("stockComboBox")
        self.monthComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.monthComboBox.setGeometry(QtCore.QRect(70, 120, 231, 32))
        self.monthComboBox.setEditable(True)
        self.monthComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.monthComboBox.setObjectName("monthComboBox")
        self.volume_2 = PlotWidget(self.centralwidget)
        self.volume_2.setGeometry(QtCore.QRect(380, 80, 591, 581))
        self.volume_2.setObjectName("volume_2")
        self.highlowPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.highlowPushButton.setGeometry(QtCore.QRect(80, 540, 201, 32))
        self.highlowPushButton.setObjectName("highlowPushButton")
        self.volumePush = QtWidgets.QPushButton(self.centralwidget)
        self.volumePush.setGeometry(QtCore.QRect(80, 900, 201, 32))
        self.volumePush.setObjectName("volumePush")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(460, 740, 481, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableHeader = QtWidgets.QLabel(self.centralwidget)
        self.tableHeader.setGeometry(QtCore.QRect(470, 700, 371, 16))
        self.tableHeader.setObjectName("tableHeader")
        QMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QMainWindow)
        self.stockComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stockComboBox.setPlaceholderText(_translate("MainWindow", "Enter Stock Name"))
        self.highlowPushButton.setText(_translate("MainWindow", "Expand"))
        self.volumePush.setText(_translate("MainWindow", "Expand"))
        self.tableHeader.setText(_translate("MainWindow", "Statistics for "))
from pyqtgraph import PlotWidget



if __name__ == "__main__":
    app = QApplication(sys.argv)
    win = Window()
    win.show()
    sys.exit(app.exec())